services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app:z
      - ./shared:/shared:z
      - server_node_modules:/app/node_modules
      - data_volume:/data
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    ports:
      - "3001:3001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app:z
      - client_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"

volumes:
  client_node_modules:
  server_node_modules:
  data_volume:
